server {
    listen       8080;
    listen  [::]:8080;
    server_name  localhost;
	autoindex off;

	location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
		add_header Andrei "Won the battle" always;
		if ( $request_method !~ ^(GET)$ ) {
			return 405;
		}
    }

	location /directory {
		rewrite ^/directory /directory/ last;
	}

#	location /directory/ {
#		alias /usr/share/nginx/html/YoupiBanane/;
#		if ($request_method != GET) { return 405; }
#		index youpi.bad_extension;
#		autoindex off;
#		try_files $uri $uri/ /directory/youpi.bad_extension =404;
#	}

	location /directory/ {
		alias /usr/share/nginx/html/YoupiBanane/;

		if ($request_method != GET) { return 405; }

		index off; # do not let nginx "discover" directories
		try_files
			$uri
			$uri/youpi.bad_extension
			/directory/youpi.bad_extension
			=404;

		location ~ \.bla$ {
			client_max_body_size 100000000;
			client_body_timeout 60s;
			default_type text/plain;
			if ($request_method = POST) {
				return 200 "CGI placeholder\n";
			}
		}
	}

	location /put_test/ {
		root /var/www/uploads;
		dav_methods PUT;
		create_full_put_path on;
		client_max_body_size 100m;
		if ($request_method != PUT) { return 405; }
	}

	location = /post_body {
		if ($request_method != POST) { return 405; }
		client_max_body_size 100;
		return 200 "ok\n";
	}

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}

