http {
	worker_processes = auto;
	log_format = main  '$remote_addr - $remote_user [$time_local] "$request" '
	'$status $body_bytes_sent "$http_referer" '
	'rt=$request_time urt=$upstream_response_time req=$request_length sent=$bytes_sent '
	'"$http_user_agent" "$http_x_forwarded_for"';
	
	server {
		listen	= 8080;
		name	= localhost;

		location / {
			root		= ./resources/web/;
			index		= index.html;
			autoindex	= false;
			methods		= GET;
			max_body_size = 3786213;

			cgi {
				ext 	= .py;
				script	= /www/blah.py;
				cgi_param = REQUEST_METHOD 	$request_method;
				cgi_param = CONTENT_LENGTH  $content_length;
			}

			cgi {
				ext 	= .php;
				script	= /www/blah.php;
				cgi_param = CONTENT_TYPE $content_type;
				cgi_param = QUERY_STRING $query_string;
			}
		}

		location /upload/ {
			root		= ./resources/web/put_test/;
			index		= index.html;
			autoindex	= true;
			methods		= PUT DELETE;
			max_body_size = 1000000000;

			cgi {
				ext 	= .php;
				script	= /www/blah.php;
			}
		}

		# location /img/ {
		# 	root		= ./img/;
		# 	index		= index.html;
		# 	autoindex	= true;
		# 	methods		= DELETE;
		# 	max_body_size = 1000000000;
		# }

		error_page = 500 502 503 504  /50x.html;
		error_page = 404 /404.html;
		error_page = 405 /405.html;
	}

	server {
		listen	= 5000;
		name	= localhost2;

		location / {
			root		= ./resources/web2/;
			index		= index.html;
			autoindex	= false;
			methods		= GET;
			max_body_size = 3786213;

			cgi {
				ext 	= .py;
				script	= /www/blah.py;
			}

			cgi {
				ext 	= .php;
				script	= /www/blah.php;
			}
		}

		location /upload {
			root		= ./resources/web/put_test/;
			index		= index.html;
			autoindex	= true;
			methods		= PUT DELETE;
			max_body_size = 1000000000;

			cgi {
				ext 	= .php;
				script	= /www/blah.php;
			}
		}
	}
}
