http {
	# worker_processes = auto;
	# log_format = main  '$remote_addr - $remote_user [$time_local] "$request" '
	# '$status $body_bytes_sent "$http_referer" '
	# 'rt=$request_time urt=$upstream_response_time req=$request_length sent=$bytes_sent '
	# '"$http_user_agent" "$http_x_forwarded_for"';

	server {
		listen	= 8080;
		name	= localhost;

		redirect = /test_redirect/ / 301;
		redirect = /put_test/ /upload/ 308;
		redirect = /hello.txt /upload/weee.txt 301;
		redirect = /directory /directory/ 301;
		redirect = /cgi-bin/ /cgi-bin/index.php 301;

		location / {
			root		= ./resources/web/;
			index		= index.html idx.html;
			autoindex	= true;
			methods		= GET; #HEAD;
			max_body_size = 3786213;
			cgi {
				ext 	= .py;
				script	= ./resources/kill.py;
				cgi_param = REQUEST_METHOD  $request_method;
				cgi_param = CONTENT_LENGTH  $content_length;
			}

			cgi {
				ext 	= .php;
				script	= /www/blah.php;
				cgi_param = CONTENT_TYPE $content_type;
				cgi_param = QUERY_STRING $query_string;
			}
			cgi {
				ext = .bla;
				cgi_pass = ./resources/cgi-bin/ubuntu_cgi_tester;
			}
		}

		location /post_body {
			root = ./resources/web/put_test;
			index = index.html;
			autoindex = false;
			methods = POST;
			max_body_size = 100;
		}

		location /cgi-bin/ {
			root = ./resources/cgi-bin/;
			index = index.php;
			autoindex = false;
			methods = GET HEAD POST;
			cgi {
				ext = .php;
				script = /cgi-bin/index.php;
			}
			cgi {
				ext = .sh;
				script = /cgi-bin/fast_echo.sh;
			}
			cgi {
				ext = .py;
				script = /cgi-bin/test.py;
			}
			cgi {
				ext = .cgi;
				script = /cgi-bin/script.cgi;
			}
		}

		location /directory/ {
			root = ./resources/web/YoupiBanane/;
			index = youpi.bad_extension;
			autoindex = false;
			methods = GET POST;
			cgi {
				ext = .bla;
				cgi_pass = ./resources/cgi-bin/ubuntu_cgi_tester;
			}
		}

		location /upload/ {
			root		= ./resources/web/put_test/;
			index		= index.html;
			autoindex	= true;
			methods		= PUT DELETE;
			max_body_size = 1000000000;

			cgi {
				ext 	= .php;
				script	= /www/blah.php;
			}
		}

		location /post_body {
			root		= ./resources/web/put_test;
			index		= index.html;
			autoindex	= false;
			methods		= POST;
			max_body_size = 1000000000;
		}

		# location /img/ {
		# 	root		= ./img/;
		# 	index		= index.html;
		# 	autoindex	= true;
		# 	methods		= DELETE;
		# 	max_body_size = 1000000000;
		# }

		error_page = 500 502 503 504  /50x.html;
		error_page = 404 /404.html;
		error_page = 405 /405.html;
	}

	server {
		listen	= 5000;
		name	= localhost2;

		location / {
			root		= ./resources/web2/;
			index		= index.html idx.html;
			autoindex	= false;
			methods		= GET HEAD;
			max_body_size = 3786213;

			cgi {
				ext 	= .py;
				script	= /www/blah.py;
			}

			cgi {
				ext 	= .php;
				script	= /www/blah.php;
			}
		}

		location /img/ {
			root		= ./resources/web/img/;
			index		= index.html;
			autoindex	= true;
			methods		= GET HEAD;
			max_body_size = 1000000000;

			cgi {
				ext 	= .php;
				script	= /www/blah.php;
			}
		}

		location /upload/ {
			root		= ./resources/web/put_test/;
			index		= index.html;
			autoindex	= true;
			methods		= PUT DELETE;
			max_body_size = 1000000000;

			cgi {
				ext 	= .php;
				script	= /www/blah.php;
			}
		}

		location /post_body {
			root		= ./resources/web/put_test;
			index		= index.html;
			autoindex	= false;
			methods		= POST;
			max_body_size = 1000000000;
		}
	}
}
